baseURL = "http://rideforsoul.com/"
languageCode = "en-us"
title = "RideForSoul"
theme = "sp_theme"

[taxonomies]
  category = "categories"
  tag = "tags"
  genres = "genres"

[menu]
  [[menu.main]]
    name = "Posts archive"
    url = "/posts"


  [[menu.main]]
    name = "Contact"
    url = "/contact"    